const quotes = [
  {id: 1, quote: 'Any fool can know. The point is to understand.', author: 'Albert Einstein' },
  {id: 2, quote: 'Tell me and I forget. Teach me and I remember. Involve me and I learn.', author: 'Benjamin Franklin' },
  {id: 3, quote: 'All the world is a laboratory to the inquiring mind.', author: 'Martin Fisher' },
  {id: 4, quote: 'It’s what you learn after you know it all that counts.', author: 'Harry S Truman' },
  {id: 5, quote: 'You don’t learn to walk by following rules. You learn by doing, and by falling over.', author: 'Richard Branson' },
  {id: 6, quote: 'It is not that I’m so smart. But I stay with the questions much longer.', author: 'Albert Einstein' },
  {id: 7, quote: 'By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.', author: 'Confucius' },
  {id: 8, quote: 'The more I read, the more I acquire, the more certain I am that I know nothing.', author: 'Voltaire' },
  {id: 9, quote: 'To endure uncertainty is difficult, but so are most of the other virtues.', author: 'Bertrand Russell' },
  {id: 10, quote: 'That which we persist in doing becomes easier for us to do; not that the nature of the thing itself is changed, but that our power to do is increased.', author: 'Ralph Waldo Emerson' },
  {id: 11, quote: 'A man who reads too much and uses his own brain too little falls into lazy habits of thinking.', author: 'Albert Einstein' },
  {id: 12, quote: 'A problem well-put is half-solved', author: 'John Dewey' },
  {id: 13, quote: 'The more that you read, the more things you will know. The more that you learn, the more places you’ll go.', author: 'Dr. Seuss' },
  {id: 14, quote: 'All learning has an emotional base.', author: 'Plato' },
  {id: 15, quote: 'Knowledge, which is acquired under compulsion, obtains no hold on the mind.', author: 'Plato' },
  {id: 16, quote: 'Wisdom is learning what to overlook.', author: 'William James' },
  {id: 17, quote: 'Knowing is not enough; We must apply. Willing is not enough; We must do.', author: 'Bruce Lee' },
  {id: 18, quote: 'Being ignorant is not so much a shame, as being unwilling to learn.', author: 'Benjamin Franklin' },
  {id: 19, quote: 'Towering genius disdains a beaten path.', author: 'Abraham Lincoln' },
  {id: 20, quote: 'Never let formal education get in the way of your learning.', author: 'Mark Twain' },
  {id: 21, quote: 'Development is a series of rebirths.', author: 'Maria Montessori' },
  {id: 22, quote: 'Man’s mind, once stretched by a new idea, never regains its original dimensions.', author: 'Oliver Wendell Holmes' },
  {id: 23, quote: 'Even the genius asks questions', author: 'Tupac Shakur' },
  {id: 24, quote: 'What you think, you become. What you feel, you attract. What you imagine, you create.', author: 'Buddha' },
  {id: 25, quote: 'The human mind is our fundamental resource.', author: 'John F. Kennedy' },
  {id: 26, quote: 'Intelligence is the ability to adapt to change.', author: 'Stephen Hawking' },
  {id: 27, quote: 'Ideas without action aren’t ideas. They’re regrets.', author: 'Steve Jobs' },
  {id: 28, quote: 'Education is not the filling of a pot but the lighting of a fire.', author: 'W.B. Yeats' },
  {id: 29, quote: 'No problem can withstand the assault of sustained thinking.', author: 'Voltaire' },
  {id: 30, quote: 'The beautiful thing about learning is that nobody can take it away from you.', author: 'B.B. King' },
  {id: 31, quote: 'An investment in knowledge pays the best interest.', author: 'Benjamin Franklin' }
];

export default quotes;